name: Cleanup Deployment

on:
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: us-east-1
      - name: Delete S3 Folder
        run: |
          FOLDER=$(awk -F\/ '{ print $3 }' <<< $GITHUB_REF)
          echo "s3://static-site-preview/${FOLDER}"
          aws s3 rm --recursive "s3://static-site-preview/${FOLDER}"
