name: Cleanup Deployment

on:
  delete

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Deployed Branch
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"
          env
