name: Deploy PR Preview

on:
  pull_request:
    branches: [ "main" ]
    types: [ "opened", "reopened", "synchronize" ]

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: ${{ steps.aws-sync.outputs.s3_url }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: us-east-1
      - name: Sync to s3
        env:
          PR_NUMBER: ${{ github.event.number }}
        id: aws-sync
        run: |
          echo "Folder: ${PR_NUMBER}"
          mkdir _dist
          echo "<h1>Git Ref: ${GITHUB_SHA}</h1>" > _dist/index.html
          aws s3 sync _dist/ "s3://static-site-preview/${PR_NUMBER}"
          echo "::set-output name=s3_url::http://static-site-preview.s3-website-us-east-1.amazonaws.com/${PR_NUMBER}"
